-- Your SQL goes here
CREATE TABLE hubs (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO hubs (name) VALUES ('default');

CREATE TABLE users (
    id INTEGER NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL,
    name VARCHAR,
    hub_id INTEGER NOT NULL REFERENCES hubs(id),
    password_hash VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(email, hub_id)
);